const fs = require('fs');
let content = fs.readFileSync('src/components/AdminDashboard.tsx', 'utf8');

// 1. Fix imports
content = content.replace("import React, { useState } from 'react';", "import React, { useState, useEffect } from 'react';");

// 2. Add state
const stateTarget = `  const [editingSlideId, setEditingSlideId] = useState<string | null>(null);`;
const stateReplacement = `  const [activityLogs, setActivityLogs] = useState<any[]>([]);
  const [loadingLogs, setLoadingLogs] = useState(false);

  useEffect(() => {
    if (activeTab === 'logs') {
      setLoadingLogs(true);
      supabase.from('activity_logs').select('*').order('created_at', { ascending: false }).limit(100)
        .then(({ data, error }) => {
          if (!error && data) {
            setActivityLogs(data);
          }
          setLoadingLogs(false);
        });
    }
  }, [activeTab]);

  const [editingSlideId, setEditingSlideId] = useState<string | null>(null);`;
content = content.replace(stateTarget, stateReplacement);

// 3. Remove badge count
content = content.replace(`if (item.id === 'logs' && dbData.logs) badgeCount = dbData.logs.length;`, ``);

// 4. Update VIEW 10
const viewTarget = `{/* VIEW 10: ACTIVITY LOGS */}
        {activeTab === 'logs' && (
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-1 border-b border-slate-200 pb-4 text-left">
              <h3 className="font-sans font-bold text-lg text-slate-900">Admin Activity Audit Logs</h3>
              <p className="text-slate-500 text-xs">Real-time log trails generated by the server. Only Super Admins can clean trails.</p>
            </div>

            <div className="bg-white backdrop-blur-md p-5 rounded-3xl border border-slate-200 font-mono text-[11px] text-slate-700 flex flex-col gap-3 text-left overflow-x-auto max-h-[450px]">
              {dbData.logs?.map((log) => (
                <div key={log.id} className="p-3 bg-slate-50 rounded-xl border border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="text-indigo-600 font-bold">🛠️ {log.action}</span>
                    <span className="text-slate-600 text-xs">Target: <strong>{log.target}</strong></span>
                    <span className="text-slate-500 text-[10px]">Executor Agent: {log.userEmail}</span>
                  </div>
                  <span className="text-[10px] text-slate-500 bg-white backdrop-blur-md border border-slate-100 px-2 py-0.5 rounded italic whitespace-nowrap shrink-0">
                    Timestamp: {log.timestamp}
                  </span>
                </div>
              ))}
              {dbData.logs?.length === 0 && (
                <div className="text-slate-500 py-6 text-center text-xs">
                  Console report clean. No operational state adjustments tracked yet.
                </div>
              )}
            </div>
          </div>
        )}`;

const viewReplacement = `{/* VIEW 10: ACTIVITY LOGS */}
        {activeTab === 'logs' && (
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-1 border-b border-slate-200 pb-4 text-left">
              <div className="flex items-center justify-between">
                <h3 className="font-sans font-bold text-lg text-slate-900">Admin Activity Audit Logs</h3>
                <span className="text-xs font-mono font-bold text-slate-400 bg-white border border-slate-200 px-3 py-1.5 rounded-lg shadow-sm">
                  {loadingLogs ? 'Loading...' : \`Showing latest \${activityLogs.length} entries\`}
                </span>
              </div>
              <p className="text-slate-500 text-xs">Real-time log trails generated by the server. Only Super Admins can clean trails.</p>
            </div>

            <div className="bg-white backdrop-blur-md p-5 rounded-3xl border border-slate-200 font-mono text-[11px] text-slate-700 flex flex-col gap-3 text-left overflow-x-auto max-h-[450px]">
              {loadingLogs && <div className="text-slate-500 py-6 text-center text-xs">Fetching logs from Supabase...</div>}
              {!loadingLogs && activityLogs.map((log) => (
                <div key={log.id} className="p-3 bg-slate-50 rounded-xl border border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="text-indigo-600 font-bold">🛠️ {log.action}</span>
                    <span className="text-slate-600 text-xs">Target: <strong>{log.target}</strong></span>
                    <span className="text-slate-500 text-[10px]">Executor Agent: {log.user_email}</span>
                  </div>
                  <span className="text-[10px] text-slate-500 bg-white backdrop-blur-md border border-slate-100 px-2 py-0.5 rounded italic whitespace-nowrap shrink-0">
                    Timestamp: {new Date(log.timestamp).toLocaleString()}
                  </span>
                </div>
              ))}
              {!loadingLogs && activityLogs.length === 0 && (
                <div className="text-slate-500 py-6 text-center text-xs">
                  Console report clean. No operational state adjustments tracked yet.
                </div>
              )}
            </div>
          </div>
        )}`;

// I noticed the source file has an emoji instead of the hammer and wrench sometimes or special characters.
// To avoid strict string matching issues with emojis, I will use regular expressions.

content = content.replace(/\{\/\* VIEW 10: ACTIVITY LOGS \*\/\}[\s\S]*?(?=\{\/\* VIEW: ADMIN CREDENTIALS MANAGEMENT \*\/\}|\{\/\* VIEW 11:)/m, viewReplacement + '\n\n        ');

fs.writeFileSync('src/components/AdminDashboard.tsx', content);
console.log('Successfully patched AdminDashboard.tsx!');
